---
- name: os-specific vars
  include_vars: "{{ansible_os_family}}.yml"
  tags:
      - always

- name: check-set-parameters
  include: kibana-parameters.yml
  tags:
      - always

- name: include java.yml
  include: java.yml
  when: kb_java_install
  tags:
      - java

- name: include kibana.yml
  include: kibana.yml
  tags:
      - install

- name: include kibana-config.yml
  include: kibana-config.yml
  tags:
      - config

- name: include kibana-plugins.yml
  include: kibana-plugins.yml
  when: kb_plugins is defined or kb_plugins_reinstall
  tags:
      - plugins

  #We always execute xpack as we may need to remove features
# - name: include xpack/kibana-xpack.yml
#   include: xpack/kibana-xpack.yml
#   tags:
#       - xpack

- name: Generate SSL/TLS environment
  include: ./kibana-xpack-ssl.yml

- name: flush handlers
  meta: flush_handlers

- name: Make sure kibana is started
  service: name=kibana state=restarted enabled=yes
  when: kb_start_service
  become: yes
