
- name: reload systemd configuration
  become: true
  command: systemctl daemon-reload

# Restart service and ensure it is enabled

- name: restart kibana
  become: true
  service: name=kibana state=restarted enabled=yes
  when:
    - kb_restart_on_change
    - kb_start_service
  register: kb_restarted
